<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MasterSeedCatalogTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Disable foreign key checks temporarily
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        
        // Clear existing data
        DB::table('master_seed_catalog')->truncate();

        // Insert data
        DB::table('master_seed_catalog')->insert([
            [
                'id' => 1,
                'common_name' => 'Sunflower',
                'cultivars' => '[\\\"Black Oilseed\\\"]',
                'category' => null,
                'aliases' => '[\\\"Black Oil\\\", \\\"sunflower\\\"]',
                'growing_notes' => null,
                'description' => null,
                'is_active' => 1,
                'created_at' => '2025-06-24 16:57:48',
                'updated_at' => '2025-06-24 16:58:18',
            ],
            [
                'id' => 2,
                'common_name' => 'Basil',
                'cultivars' => '[\\\"Genovese\\\", \\\"Thai\\\"]',
                'category' => null,
                'aliases' => null,
                'growing_notes' => null,
                'description' => null,
                'is_active' => 1,
                'created_at' => '2025-06-24 21:14:14',
                'updated_at' => '2025-06-24 21:14:14',
            ],
            [
                'id' => 3,
                'common_name' => 'Amaranth',
                'cultivars' => '[\\\"Red\\\"]',
                'category' => null,
                'aliases' => null,
                'growing_notes' => null,
                'description' => null,
                'is_active' => 1,
                'created_at' => '2025-06-25 13:22:14',
                'updated_at' => '2025-06-25 13:22:14',
            ],
            [
                'id' => 4,
                'common_name' => 'Arugula',
                'cultivars' => '[\\\"Arugula\\\"]',
                'category' => null,
                'aliases' => null,
                'growing_notes' => null,
                'description' => null,
                'is_active' => 1,
                'created_at' => '2025-06-25 13:22:14',
                'updated_at' => '2025-06-25 13:22:14',
            ],
            [
                'id' => 5,
                'common_name' => 'Beet',
                'cultivars' => '[\\\"Bull\\\\u2019s Blood\\\",\\\"Pink\\\",\\\"Ruby\\\"]',
                'category' => null,
                'aliases' => null,
                'growing_notes' => null,
                'description' => null,
                'is_active' => 1,
                'created_at' => '2025-06-25 13:22:14',
                'updated_at' => '2025-06-25 13:22:14',
            ],
            [
                'id' => 6,
                'common_name' => 'Borage',
                'cultivars' => '[\\\"Borage\\\"]',
                'category' => null,
                'aliases' => null,
                'growing_notes' => null,
                'description' => null,
                'is_active' => 1,
                'created_at' => '2025-06-25 13:22:37',
                'updated_at' => '2025-06-25 13:22:37',
            ],
            [
                'id' => 7,
                'common_name' => 'Broccoli',
                'cultivars' => '[\\\"Broccoli\\\"]',
                'category' => null,
                'aliases' => null,
                'growing_notes' => null,
                'description' => null,
                'is_active' => 1,
                'created_at' => '2025-06-25 13:22:37',
                'updated_at' => '2025-06-25 13:22:37',
            ],
            [
                'id' => 8,
                'common_name' => 'Cabbage',
                'cultivars' => '[\\\"Red\\\"]',
                'category' => null,
                'aliases' => null,
                'growing_notes' => null,
                'description' => null,
                'is_active' => 1,
                'created_at' => '2025-06-25 13:22:37',
                'updated_at' => '2025-06-25 13:22:37',
            ],
            [
                'id' => 9,
                'common_name' => 'Clover',
                'cultivars' => '[\\\"Red\\\"]',
                'category' => null,
                'aliases' => null,
                'growing_notes' => null,
                'description' => null,
                'is_active' => 1,
                'created_at' => '2025-06-25 13:23:55',
                'updated_at' => '2025-06-25 13:23:55',
            ],
            [
                'id' => 10,
                'common_name' => 'Coriander',
                'cultivars' => '[\\\"Coriander\\\"]',
                'category' => null,
                'aliases' => null,
                'growing_notes' => null,
                'description' => null,
                'is_active' => 1,
                'created_at' => '2025-06-25 13:23:55',
                'updated_at' => '2025-06-25 13:23:55',
            ],
            [
                'id' => 11,
                'common_name' => 'Cress',
                'cultivars' => '[\\\"Curly (Garden )\\\"]',
                'category' => null,
                'aliases' => null,
                'growing_notes' => null,
                'description' => null,
                'is_active' => 1,
                'created_at' => '2025-06-25 13:23:55',
                'updated_at' => '2025-06-25 13:23:55',
            ],
            [
                'id' => 12,
                'common_name' => 'Dill',
                'cultivars' => '[\\\"Dill\\\"]',
                'category' => null,
                'aliases' => null,
                'growing_notes' => null,
                'description' => null,
                'is_active' => 1,
                'created_at' => '2025-06-25 13:23:55',
                'updated_at' => '2025-06-25 13:23:55',
            ],
            [
                'id' => 13,
                'common_name' => 'Fava',
                'cultivars' => '[\\\"Beans\\\"]',
                'category' => null,
                'aliases' => null,
                'growing_notes' => null,
                'description' => null,
                'is_active' => 1,
                'created_at' => '2025-06-25 13:23:55',
                'updated_at' => '2025-06-25 13:23:55',
            ],
            [
                'id' => 14,
                'common_name' => 'Fennel',
                'cultivars' => '[\\\"Fennel\\\"]',
                'category' => null,
                'aliases' => null,
                'growing_notes' => null,
                'description' => null,
                'is_active' => 1,
                'created_at' => '2025-06-25 13:23:55',
                'updated_at' => '2025-06-25 13:23:55',
            ],
            [
                'id' => 15,
                'common_name' => 'Fenugreek',
                'cultivars' => '[\\\"Fenugreek\\\"]',
                'category' => null,
                'aliases' => null,
                'growing_notes' => null,
                'description' => null,
                'is_active' => 1,
                'created_at' => '2025-06-25 13:23:55',
                'updated_at' => '2025-06-25 13:23:55',
            ],
            [
                'id' => 16,
                'common_name' => 'Kale',
                'cultivars' => '[\\\"Green\\\",\\\"Red\\\"]',
                'category' => null,
                'aliases' => null,
                'growing_notes' => null,
                'description' => null,
                'is_active' => 1,
                'created_at' => '2025-06-25 13:23:55',
                'updated_at' => '2025-06-25 13:23:55',
            ],
            [
                'id' => 17,
                'common_name' => 'Kohlrabi',
                'cultivars' => '[\\\"Purple\\\"]',
                'category' => null,
                'aliases' => null,
                'growing_notes' => null,
                'description' => null,
                'is_active' => 1,
                'created_at' => '2025-06-25 13:23:55',
                'updated_at' => '2025-06-25 13:23:55',
            ],
            [
                'id' => 18,
                'common_name' => 'Komatsuna',
                'cultivars' => '[\\\"Komatsuna\\\"]',
                'category' => null,
                'aliases' => null,
                'growing_notes' => null,
                'description' => null,
                'is_active' => 1,
                'created_at' => '2025-06-25 13:23:55',
                'updated_at' => '2025-06-25 13:23:55',
            ],
            [
                'id' => 19,
                'common_name' => 'Mustard',
                'cultivars' => '[\\\"Oriental\\\"]',
                'category' => null,
                'aliases' => null,
                'growing_notes' => null,
                'description' => null,
                'is_active' => 1,
                'created_at' => '2025-06-25 13:23:55',
                'updated_at' => '2025-06-25 13:23:55',
            ],
            [
                'id' => 20,
                'common_name' => 'Peas,',
                'cultivars' => '[\\\"Speckled\\\"]',
                'category' => null,
                'aliases' => null,
                'growing_notes' => null,
                'description' => null,
                'is_active' => 1,
                'created_at' => '2025-06-25 13:23:55',
                'updated_at' => '2025-06-25 13:23:55',
            ],
            [
                'id' => 21,
                'common_name' => 'Radish',
                'cultivars' => '[\\\"Red\\\",\\\"Ruby Stem\\\"]',
                'category' => null,
                'aliases' => null,
                'growing_notes' => null,
                'description' => null,
                'is_active' => 1,
                'created_at' => '2025-06-25 13:23:55',
                'updated_at' => '2025-06-25 13:23:55',
            ],
        ]);
        
        // Re-enable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}