-- MySQL dump 10.13  Distrib 9.3.0, for macos15.4 (arm64)
--
-- Host: 127.0.0.1    Database: catapult
-- ------------------------------------------------------
-- Server version	8.0.33

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Dumping data for table `seed_entries`
--

LOCK TABLES `seed_entries` WRITE;
/*!40000 ALTER TABLE `seed_entries` DISABLE KEYS */;
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (1,NULL,'Red','Amaranth',1,'Amaranth, Red','https://sprouting.com/product/amaranth-red/',NULL,NULL,'[]',1,'2025-06-24 23:05:14','2025-06-24 23:05:14');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (2,NULL,'Arugula','Arugula',1,'Arugula','https://sprouting.com/product/arugula/',NULL,NULL,'[]',1,'2025-06-24 23:05:14','2025-06-24 23:05:14');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (3,NULL,'Rocky Wild','Arugula',1,'Arugula, Rocky Wild','https://sprouting.com/product/arugula-rocky-wild/',NULL,NULL,'[]',1,'2025-06-24 23:05:14','2025-06-24 23:05:14');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (4,NULL,'Barley','Barley',1,'Barley, hulls on','https://sprouting.com/product/barley-hulls-on/',NULL,NULL,'[]',1,'2025-06-24 23:05:14','2025-06-24 23:05:14');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (5,NULL,'Genovese','Basil',1,'Basil, Genovese','https://sprouting.com/product/basil-genovese/',NULL,NULL,'[]',1,'2025-06-24 23:05:14','2025-06-24 23:05:14');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (6,NULL,'Purple','Basil',1,'Basil, Purple','https://sprouting.com/product/basil-purple/',NULL,NULL,'[]',1,'2025-06-24 23:05:14','2025-06-24 23:05:14');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (7,NULL,'Thai','Basil',1,'Basil, Thai','https://sprouting.com/product/basil-thai/',NULL,NULL,'[]',1,'2025-06-24 23:05:14','2025-06-24 23:05:14');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (8,NULL,'Bull’s Blood','Beet',1,'Beet, Bull’s Blood','https://sprouting.com/product/beet-bulls-blood/',NULL,NULL,'[]',1,'2025-06-24 23:05:15','2025-06-24 23:05:15');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (9,NULL,'Pink','Beet',1,'Beet, Pink','https://sprouting.com/product/beet-pink/',NULL,NULL,'[]',1,'2025-06-24 23:05:15','2025-06-24 23:05:15');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (10,NULL,'Ruby','Beet',1,'Beet, Ruby','https://sprouting.com/product/beet-ruby/',NULL,NULL,'[]',1,'2025-06-24 23:05:15','2025-06-24 23:05:15');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (11,NULL,'(Pak Choi)','Bok Choy',1,'Bok Choy (Pak Choi)','https://sprouting.com/product/bok-choy-pak-choi/',NULL,NULL,'[]',1,'2025-06-24 23:05:15','2025-06-24 23:05:15');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (12,NULL,'Borage','Borage',1,'Borage','https://sprouting.com/product/borage/',NULL,NULL,'[]',1,'2025-06-24 23:05:15','2025-06-24 23:05:15');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (13,NULL,'Blend','Brilliant',1,'Brilliant Blend','https://sprouting.com/product/brilliant-blend/',NULL,NULL,'[]',1,'2025-06-24 23:05:15','2025-06-24 23:05:15');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (14,NULL,'Broccoli','Broccoli',1,'Broccoli','https://sprouting.com/product/broccoli/',NULL,NULL,'[]',1,'2025-06-24 23:05:15','2025-06-24 23:05:15');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (15,NULL,'Raab (Rapini)','Broccoli',1,'Broccoli Raab (Rapini)','https://sprouting.com/product/broccoli-raab-rapini/',NULL,NULL,'[]',1,'2025-06-24 23:05:15','2025-06-24 23:05:15');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (16,NULL,'Buckwheat','Buckwheat',1,'Buckwheat','https://sprouting.com/product/buckwheat/',NULL,NULL,'[]',1,'2025-06-24 23:05:15','2025-06-24 23:05:15');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (17,NULL,'Red','Cabbage',1,'Cabbage, Red','https://sprouting.com/product/cabbage-red/',NULL,NULL,'[]',1,'2025-06-24 23:05:15','2025-06-24 23:05:15');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (18,NULL,'Carrot','Carrot',1,'Carrot','https://sprouting.com/product/carrot/',NULL,NULL,'[]',1,'2025-06-24 23:05:15','2025-06-24 23:05:15');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (19,NULL,'Celery','Celery',1,'Celery','https://sprouting.com/product/celery/',NULL,NULL,'[]',1,'2025-06-24 23:05:15','2025-06-24 23:05:15');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (20,NULL,'Chervil','Chervil',1,'Chervil','https://sprouting.com/product/chervil/',NULL,NULL,'[]',1,'2025-06-24 23:05:15','2025-06-24 23:05:15');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (21,NULL,'Black','Chia',1,'Chia, Black','https://sprouting.com/product/chia-black/',NULL,NULL,'[]',1,'2025-06-24 23:05:15','2025-06-24 23:05:15');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (22,NULL,'Chicory','Chicory',1,'Chicory','https://sprouting.com/product/chicory/',NULL,NULL,'[]',1,'2025-06-24 23:05:15','2025-06-24 23:05:15');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (23,NULL,'Crimson','Clover',1,'Clover, Crimson','https://sprouting.com/product/clover-crimson/',NULL,NULL,'[]',1,'2025-06-24 23:05:15','2025-06-24 23:05:15');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (24,NULL,'Red','Clover',1,'Clover, Red','https://sprouting.com/product/clover-red/',NULL,NULL,'[]',1,'2025-06-24 23:05:15','2025-06-24 23:05:15');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (25,NULL,'Collard','Collard',1,'Collard','https://sprouting.com/product/collard/',NULL,NULL,'[]',1,'2025-06-24 23:05:15','2025-06-24 23:05:15');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (26,NULL,'Coriander','Coriander',1,'Coriander','https://sprouting.com/product/coriander/',NULL,NULL,'[]',1,'2025-06-24 23:05:15','2025-06-24 23:05:15');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (27,NULL,'Corn Salad','Corn Salad',1,'Corn Salad (Mache)','https://sprouting.com/product/corn-salad/',NULL,NULL,'[]',1,'2025-06-24 23:05:15','2025-06-24 23:05:15');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (28,NULL,'Cranberry','Bean',1,'Cranberry Bean','https://sprouting.com/product/cranberry-bean/',NULL,NULL,'[]',1,'2025-06-24 23:05:15','2025-06-24 23:05:15');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (29,NULL,'Curly (Garden )','Cress',1,'Curly Cress (Garden Cress)','https://sprouting.com/product/curly-cress/',NULL,NULL,'[]',1,'2025-06-24 23:05:15','2025-06-24 23:05:15');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (30,NULL,'Dill','Dill',1,'Dill','https://sprouting.com/product/dill/',NULL,NULL,'[]',1,'2025-06-24 23:05:15','2025-06-24 23:05:15');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (31,NULL,'Endive','Endive',1,'Endive','https://sprouting.com/product/endive/',NULL,NULL,'[]',1,'2025-06-24 23:05:15','2025-06-24 23:05:15');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (32,NULL,'Beans','Fava',1,'Fava Beans','https://sprouting.com/product/fava-beans/',NULL,NULL,'[]',1,'2025-06-24 23:05:15','2025-06-24 23:05:15');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (33,NULL,'Fennel','Fennel',1,'Fennel','https://sprouting.com/product/fennel/',NULL,NULL,'[]',1,'2025-06-24 23:05:16','2025-06-24 23:05:16');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (34,NULL,'Fenugreek','Fenugreek',1,'Fenugreek','https://sprouting.com/product/fenugreek/',NULL,NULL,'[]',1,'2025-06-24 23:05:16','2025-06-24 23:05:16');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (35,NULL,'Garlic Chives','Garlic Chives',1,'Garlic Chives','https://sprouting.com/product/garlic-chives/',NULL,NULL,'[]',1,'2025-06-24 23:05:16','2025-06-24 23:05:16');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (36,NULL,'Green','Kale',1,'Kale, Green','https://sprouting.com/product/kale-green/',NULL,NULL,'[]',1,'2025-06-24 23:05:16','2025-06-24 23:05:16');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (37,NULL,'Red','Kale',1,'Kale, Red','https://sprouting.com/product/kale-red/',NULL,NULL,'[]',1,'2025-06-24 23:05:16','2025-06-24 23:05:16');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (38,NULL,'Kamut','Kamut',1,'Kamut®','https://sprouting.com/product/kamut/',NULL,NULL,'[]',1,'2025-06-24 23:05:16','2025-06-24 23:05:16');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (39,NULL,'Purple','Kohlrabi',1,'Kohlrabi, Purple','https://sprouting.com/product/kohlrabi-purple/',NULL,NULL,'[]',1,'2025-06-24 23:05:16','2025-06-24 23:05:16');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (40,NULL,'Komatsuna','Komatsuna',1,'Komatsuna','https://sprouting.com/product/komatsuna/',NULL,NULL,'[]',1,'2025-06-24 23:05:16','2025-06-24 23:05:16');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (41,NULL,'Purple','Komatsuna',1,'Komatsuna, Purple','https://sprouting.com/product/purple-komatsuna/',NULL,NULL,'[]',1,'2025-06-24 23:05:16','2025-06-24 23:05:16');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (42,NULL,'Leek','Leek',1,'Leek','https://sprouting.com/product/leek/',NULL,NULL,'[]',1,'2025-06-24 23:05:16','2025-06-24 23:05:16');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (43,NULL,'Lemon Balm','Lemon Balm',1,'Lemon Balm','https://sprouting.com/product/lemon-balm/',NULL,NULL,'[]',1,'2025-06-24 23:05:16','2025-06-24 23:05:16');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (44,NULL,'Black','Lentils,',1,'Lentils, Black','https://sprouting.com/product/lentils-black/',NULL,NULL,'[]',1,'2025-06-24 23:05:16','2025-06-24 23:05:16');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (45,NULL,'Crimson','Lentils,',1,'Lentils, Crimson','https://sprouting.com/product/lentils-crimson/',NULL,NULL,'[]',1,'2025-06-24 23:05:16','2025-06-24 23:05:16');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (46,NULL,'French','Lentils,',1,'Lentils, French','https://sprouting.com/product/lentils-french/',NULL,NULL,'[]',1,'2025-06-24 23:05:16','2025-06-24 23:05:16');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (47,NULL,'Large Green','Lentils,',1,'Lentils, Large Green','https://sprouting.com/product/lentils-large-green/',NULL,NULL,'[]',1,'2025-06-24 23:05:16','2025-06-24 23:05:16');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (48,NULL,'Small Green','Lentils,',1,'Lentils, Small Green','https://sprouting.com/product/lentils-small-green/',NULL,NULL,'[]',1,'2025-06-24 23:05:16','2025-06-24 23:05:16');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (49,NULL,'Mellow Microgreen Mix','Mellow Microgreen Mix',1,'Mellow Microgreen Mix','https://sprouting.com/product/mellow-microgreen-mix/',NULL,NULL,'[]',1,'2025-06-24 23:05:16','2025-06-24 23:05:16');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (50,NULL,'Microgreen Salad Mix','Microgreen Salad Mix',1,'Microgreen Salad Mix','https://sprouting.com/product/microgreen-salad-mix/',NULL,NULL,'[]',1,'2025-06-24 23:05:16','2025-06-24 23:05:16');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (51,NULL,'Beans','Mung',1,'Mung Beans','https://sprouting.com/product/mung-beans/',NULL,NULL,'[]',1,'2025-06-24 23:05:16','2025-06-24 23:05:16');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (52,NULL,'Brown','Mustard',1,'Mustard, Brown','https://sprouting.com/product/mustard-brown/',NULL,NULL,'[]',1,'2025-06-24 23:05:16','2025-06-24 23:05:16');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (53,NULL,'Mizuna','Mustard',1,'Mustard, Mizuna','https://sprouting.com/product/mustard-mizuna/',NULL,NULL,'[]',1,'2025-06-24 23:05:16','2025-06-24 23:05:16');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (54,NULL,'Oriental','Mustard',1,'Mustard, Oriental','https://sprouting.com/product/mustard-oriental/',NULL,NULL,'[]',1,'2025-06-24 23:05:16','2025-06-24 23:05:16');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (55,NULL,'Red','Mustard',1,'Mustard, Red','https://sprouting.com/product/mustard-red/',NULL,NULL,'[]',1,'2025-06-24 23:05:16','2025-06-24 23:05:16');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (56,NULL,'Red Mizuna','Mustard',1,'Mustard, Red Mizuna','https://sprouting.com/product/mustard-red-mizuna/',NULL,NULL,'[]',1,'2025-06-24 23:05:16','2025-06-24 23:05:16');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (57,NULL,'Ruby Streaks','Mustard',1,'Mustard, Ruby Streaks','https://sprouting.com/product/mustard-scarlett-frills/',NULL,NULL,'[]',1,'2025-06-24 23:05:16','2025-06-24 23:05:16');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (58,NULL,'Tat Soi','Mustard',1,'Mustard, Tat Soi','https://sprouting.com/product/mustard-tat-soi/',NULL,NULL,'[]',1,'2025-06-24 23:05:17','2025-06-24 23:05:17');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (59,NULL,'Tokyo Bekana','Mustard',1,'Mustard, Tokyo Bekana','https://sprouting.com/product/mustard-tokyo-bekana/',NULL,NULL,'[]',1,'2025-06-24 23:05:17','2025-06-24 23:05:17');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (60,NULL,'Yellow','Mustard',1,'Mustard, Yellow','https://sprouting.com/product/mustard-yellow/',NULL,NULL,'[]',1,'2025-06-24 23:05:17','2025-06-24 23:05:17');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (61,NULL,'Emerald','Nasturtium',1,'Nasturtium, Emerald','https://sprouting.com/product/nasturtium/',NULL,NULL,'[]',1,'2025-06-24 23:05:17','2025-06-24 23:05:17');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (62,NULL,'Red','Nasturtium',1,'Nasturtium, Red','https://sprouting.com/product/red-nasturtium/',NULL,NULL,'[]',1,'2025-06-24 23:05:17','2025-06-24 23:05:17');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (63,NULL,'Hulless','Oats,',1,'Oats, Hulless','https://sprouting.com/product/oats-hulless/',NULL,NULL,'[]',1,'2025-06-24 23:05:17','2025-06-24 23:05:17');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (64,NULL,'Onion','Onion',1,'Onion','https://sprouting.com/product/onion/',NULL,NULL,'[]',1,'2025-06-24 23:05:17','2025-06-24 23:05:17');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (65,NULL,'Parsley','Parsley',1,'Parsley','https://sprouting.com/product/parsley/',NULL,NULL,'[]',1,'2025-06-24 23:05:17','2025-06-24 23:05:17');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (66,NULL,'Dwarf Grey Sugar','Peas,',1,'Peas, Dwarf Grey Sugar','https://sprouting.com/product/peas-dwarf-grey-sugar/',NULL,NULL,'[]',1,'2025-06-24 23:05:17','2025-06-24 23:05:17');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (67,NULL,'Green','Peas,',1,'Peas, Green','https://sprouting.com/product/peas-green/',NULL,NULL,'[]',1,'2025-06-24 23:05:17','2025-06-24 23:05:17');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (68,NULL,'Oregon Giant','Peas,',1,'Peas, Oregon Giant','https://sprouting.com/product/peas-oregon-giant/',NULL,NULL,'[]',1,'2025-06-24 23:05:17','2025-06-24 23:05:17');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (69,NULL,'Speckled','Peas,',1,'Peas, Speckled','https://sprouting.com/product/peas-speckled/',NULL,NULL,'[]',1,'2025-06-24 23:05:17','2025-06-24 23:05:17');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (70,NULL,'Yellow','Peas,',1,'Peas, Yellow','https://sprouting.com/product/peas-yellow/',NULL,NULL,'[]',1,'2025-06-24 23:05:17','2025-06-24 23:05:17');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (71,NULL,'Popcorn','Popcorn',1,'Popcorn','https://sprouting.com/product/popcorn/',NULL,NULL,'[]',1,'2025-06-24 23:05:17','2025-06-24 23:05:17');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (72,NULL,'Daikon','Radish',1,'Radish, Daikon','https://sprouting.com/product/radish-daikon/',NULL,NULL,'[]',1,'2025-06-24 23:05:17','2025-06-24 23:05:17');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (73,NULL,'Red','Radish',1,'Radish, Red','https://sprouting.com/product/radish-red/',NULL,NULL,'[]',1,'2025-06-24 23:05:17','2025-06-24 23:05:17');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (74,NULL,'Ruby Stem','Radish',1,'Radish, Ruby Stem','https://sprouting.com/product/radish-ruby-stem/',NULL,NULL,'[]',1,'2025-06-24 23:05:17','2025-06-24 23:05:17');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (75,NULL,'Triton','Radish',1,'Radish, Triton','https://sprouting.com/product/radish-triton/',NULL,NULL,'[]',1,'2025-06-24 23:05:17','2025-06-24 23:05:17');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (76,NULL,'Rainbow','Radish',1,'Rainbow Radish','https://sprouting.com/product/rainbow-radish/',NULL,NULL,'[]',1,'2025-06-24 23:05:17','2025-06-24 23:05:17');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (77,NULL,'Red Shiso','Red Shiso',1,'Red Shiso (Perilla)','https://sprouting.com/product/perilla/',NULL,NULL,'[]',1,'2025-06-24 23:05:17','2025-06-24 23:05:17');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (78,NULL,'Microgreen Blend','Spicy',1,'Spicy Microgreen Blend','https://sprouting.com/product/spicy-microgreen-blend/',NULL,NULL,'[]',1,'2025-06-24 23:05:17','2025-06-24 23:05:17');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (79,NULL,'Spigarello','Spigarello',1,'Spigarello','https://sprouting.com/product/spigarello/',NULL,NULL,'[]',1,'2025-06-24 23:05:17','2025-06-24 23:05:17');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (80,NULL,'Black Oilseed','Sunflower',1,'Sunflower, Black Oilseed','https://sprouting.com/product/sunflower-black-oilseed/',NULL,NULL,'[]',1,'2025-06-24 23:05:17','2025-06-24 23:05:17');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (81,NULL,'Red','Swiss Chard',1,'Swiss Chard, Red','https://sprouting.com/product/swiss-chard-ruby/',NULL,NULL,'[]',1,'2025-06-24 23:05:17','2025-06-24 23:05:17');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (82,NULL,'Yellow','Swiss Chard',1,'Swiss Chard, Yellow','https://sprouting.com/product/swiss-chard-yellow/',NULL,NULL,'[]',1,'2025-06-24 23:05:17','2025-06-24 23:05:17');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (83,NULL,'Thyme','Thyme',1,'Thyme','https://sprouting.com/product/thyme/',NULL,NULL,'[]',1,'2025-06-24 23:05:17','2025-06-24 23:05:17');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (84,NULL,'Turnip','Turnip',1,'Turnip','https://sprouting.com/product/turnip/',NULL,NULL,'[]',1,'2025-06-24 23:05:17','2025-06-24 23:05:17');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (85,NULL,'Watercress','Watercress',1,'Watercress','https://sprouting.com/product/watercress/',NULL,NULL,'[]',1,'2025-06-24 23:05:18','2025-06-24 23:05:18');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (86,NULL,'Hard Red Spring','Wheat',1,'Wheat, Hard Red Spring','https://sprouting.com/product/wheat-hard-red-spring/',NULL,NULL,'[]',1,'2025-06-24 23:05:18','2025-06-24 23:05:18');
INSERT INTO `seed_entries` (`id`, `seed_cultivar_id`, `cultivar_name`, `common_name`, `supplier_id`, `supplier_product_title`, `supplier_product_url`, `image_url`, `description`, `tags`, `is_active`, `created_at`, `updated_at`) VALUES (87,NULL,'Hard Red Winter','Wheat',1,'Wheat, Hard Red Winter','https://sprouting.com/product/wheat-hard-red-winter/',NULL,NULL,'[]',1,'2025-06-24 23:05:18','2025-06-24 23:05:18');
/*!40000 ALTER TABLE `seed_entries` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2025-06-28 19:48:24
