<?php

namespace Database\Seeders\Legacy;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TaskTypesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clear existing data
        DB::table('task_types')->truncate();

        // Insert data
        DB::table('task_types')->insert([
            [
                'id' => 1,
                'name' => 'Planting Seeds',
                'category' => 'growing',
                'sort_order' => 1,
                'is_active' => 1,
                'created_at' => '2025-06-24 22:11:08',
                'updated_at' => '2025-06-24 22:11:08',
            ],
            [
                'id' => 2,
                'name' => 'Watering',
                'category' => 'growing',
                'sort_order' => 2,
                'is_active' => 1,
                'created_at' => '2025-06-24 22:11:08',
                'updated_at' => '2025-06-24 22:11:08',
            ],
            [
                'id' => 3,
                'name' => 'Harvesting',
                'category' => 'growing',
                'sort_order' => 3,
                'is_active' => 1,
                'created_at' => '2025-06-24 22:11:08',
                'updated_at' => '2025-06-24 22:11:08',
            ],
            [
                'id' => 4,
                'name' => 'Washing Trays',
                'category' => 'growing',
                'sort_order' => 4,
                'is_active' => 1,
                'created_at' => '2025-06-24 22:11:08',
                'updated_at' => '2025-06-24 22:11:08',
            ],
            [
                'id' => 5,
                'name' => 'Making Trays',
                'category' => 'growing',
                'sort_order' => 5,
                'is_active' => 1,
                'created_at' => '2025-06-24 22:11:08',
                'updated_at' => '2025-06-24 22:11:08',
            ],
            [
                'id' => 6,
                'name' => 'Making Soil',
                'category' => 'growing',
                'sort_order' => 6,
                'is_active' => 1,
                'created_at' => '2025-06-24 22:11:08',
                'updated_at' => '2025-06-24 22:11:08',
            ],
            [
                'id' => 7,
                'name' => 'Seed Soaking',
                'category' => 'growing',
                'sort_order' => 7,
                'is_active' => 1,
                'created_at' => '2025-06-24 22:11:08',
                'updated_at' => '2025-06-24 22:11:08',
            ],
            [
                'id' => 8,
                'name' => 'Transplanting',
                'category' => 'growing',
                'sort_order' => 8,
                'is_active' => 1,
                'created_at' => '2025-06-24 22:11:08',
                'updated_at' => '2025-06-24 22:11:08',
            ],
            [
                'id' => 9,
                'name' => 'Quality Control',
                'category' => 'growing',
                'sort_order' => 9,
                'is_active' => 1,
                'created_at' => '2025-06-24 22:11:08',
                'updated_at' => '2025-06-24 22:11:08',
            ],
            [
                'id' => 10,
                'name' => 'Cleaning Growing Area',
                'category' => 'maintenance',
                'sort_order' => 1,
                'is_active' => 1,
                'created_at' => '2025-06-24 22:11:08',
                'updated_at' => '2025-06-24 22:11:08',
            ],
            [
                'id' => 11,
                'name' => 'Equipment Maintenance',
                'category' => 'maintenance',
                'sort_order' => 2,
                'is_active' => 1,
                'created_at' => '2025-06-24 22:11:08',
                'updated_at' => '2025-06-24 22:11:08',
            ],
            [
                'id' => 12,
                'name' => 'Organizing Supplies',
                'category' => 'maintenance',
                'sort_order' => 3,
                'is_active' => 1,
                'created_at' => '2025-06-24 22:11:08',
                'updated_at' => '2025-06-24 22:11:08',
            ],
            [
                'id' => 13,
                'name' => 'Sanitizing Equipment',
                'category' => 'maintenance',
                'sort_order' => 4,
                'is_active' => 1,
                'created_at' => '2025-06-24 22:11:09',
                'updated_at' => '2025-06-24 22:11:09',
            ],
            [
                'id' => 14,
                'name' => 'Waste Management',
                'category' => 'maintenance',
                'sort_order' => 5,
                'is_active' => 1,
                'created_at' => '2025-06-24 22:11:09',
                'updated_at' => '2025-06-24 22:11:09',
            ],
            [
                'id' => 15,
                'name' => 'Temperature Control',
                'category' => 'maintenance',
                'sort_order' => 6,
                'is_active' => 1,
                'created_at' => '2025-06-24 22:11:09',
                'updated_at' => '2025-06-24 22:11:09',
            ],
            [
                'id' => 16,
                'name' => 'Humidity Control',
                'category' => 'maintenance',
                'sort_order' => 7,
                'is_active' => 1,
                'created_at' => '2025-06-24 22:11:09',
                'updated_at' => '2025-06-24 22:11:09',
            ],
            [
                'id' => 17,
                'name' => 'Computer Work',
                'category' => 'administrative',
                'sort_order' => 1,
                'is_active' => 1,
                'created_at' => '2025-06-24 22:11:09',
                'updated_at' => '2025-06-24 22:11:09',
            ],
            [
                'id' => 18,
                'name' => 'Bookkeeping',
                'category' => 'administrative',
                'sort_order' => 2,
                'is_active' => 1,
                'created_at' => '2025-06-24 22:11:09',
                'updated_at' => '2025-06-24 22:11:09',
            ],
            [
                'id' => 19,
                'name' => 'Invoicing',
                'category' => 'administrative',
                'sort_order' => 3,
                'is_active' => 1,
                'created_at' => '2025-06-24 22:11:09',
                'updated_at' => '2025-06-24 22:11:09',
            ],
            [
                'id' => 20,
                'name' => 'Customer Communication',
                'category' => 'administrative',
                'sort_order' => 4,
                'is_active' => 1,
                'created_at' => '2025-06-24 22:11:09',
                'updated_at' => '2025-06-24 22:11:09',
            ],
            [
                'id' => 21,
                'name' => 'Inventory Management',
                'category' => 'administrative',
                'sort_order' => 5,
                'is_active' => 1,
                'created_at' => '2025-06-24 22:11:09',
                'updated_at' => '2025-06-24 22:11:09',
            ],
            [
                'id' => 22,
                'name' => 'Order Processing',
                'category' => 'administrative',
                'sort_order' => 6,
                'is_active' => 1,
                'created_at' => '2025-06-24 22:11:09',
                'updated_at' => '2025-06-24 22:11:09',
            ],
            [
                'id' => 23,
                'name' => 'Data Entry',
                'category' => 'administrative',
                'sort_order' => 7,
                'is_active' => 1,
                'created_at' => '2025-06-24 22:11:09',
                'updated_at' => '2025-06-24 22:11:09',
            ],
            [
                'id' => 24,
                'name' => 'Planning & Scheduling',
                'category' => 'administrative',
                'sort_order' => 8,
                'is_active' => 1,
                'created_at' => '2025-06-24 22:11:09',
                'updated_at' => '2025-06-24 22:11:09',
            ],
            [
                'id' => 25,
                'name' => 'Packaging Products',
                'category' => 'packaging',
                'sort_order' => 1,
                'is_active' => 1,
                'created_at' => '2025-06-24 22:11:09',
                'updated_at' => '2025-06-24 22:11:09',
            ],
            [
                'id' => 26,
                'name' => 'Labeling',
                'category' => 'packaging',
                'sort_order' => 2,
                'is_active' => 1,
                'created_at' => '2025-06-24 22:11:09',
                'updated_at' => '2025-06-24 22:11:09',
            ],
            [
                'id' => 27,
                'name' => 'Delivery Preparation',
                'category' => 'packaging',
                'sort_order' => 3,
                'is_active' => 1,
                'created_at' => '2025-06-24 22:11:09',
                'updated_at' => '2025-06-24 22:11:09',
            ],
            [
                'id' => 28,
                'name' => 'Delivery',
                'category' => 'packaging',
                'sort_order' => 4,
                'is_active' => 1,
                'created_at' => '2025-06-24 22:11:09',
                'updated_at' => '2025-06-24 22:11:09',
            ],
            [
                'id' => 29,
                'name' => 'Loading/Unloading',
                'category' => 'packaging',
                'sort_order' => 5,
                'is_active' => 1,
                'created_at' => '2025-06-24 22:11:09',
                'updated_at' => '2025-06-24 22:11:09',
            ],
            [
                'id' => 30,
                'name' => 'Team Meeting',
                'category' => 'other',
                'sort_order' => 1,
                'is_active' => 1,
                'created_at' => '2025-06-24 22:11:09',
                'updated_at' => '2025-06-24 22:11:09',
            ],
            [
                'id' => 31,
                'name' => 'Training',
                'category' => 'other',
                'sort_order' => 2,
                'is_active' => 1,
                'created_at' => '2025-06-24 22:11:09',
                'updated_at' => '2025-06-24 22:11:09',
            ],
            [
                'id' => 32,
                'name' => 'Research & Development',
                'category' => 'other',
                'sort_order' => 3,
                'is_active' => 1,
                'created_at' => '2025-06-24 22:11:09',
                'updated_at' => '2025-06-24 22:11:09',
            ],
            [
                'id' => 33,
                'name' => 'Supplier Communication',
                'category' => 'other',
                'sort_order' => 4,
                'is_active' => 1,
                'created_at' => '2025-06-24 22:11:09',
                'updated_at' => '2025-06-24 22:11:09',
            ],
            [
                'id' => 34,
                'name' => 'Break Time',
                'category' => 'other',
                'sort_order' => 5,
                'is_active' => 1,
                'created_at' => '2025-06-24 22:11:09',
                'updated_at' => '2025-06-24 22:11:09',
            ],
        ]);
    }
}